[project]
name = "netra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anchit Gupta", email = "anchitgupta1107@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
netra = "netra:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
